version: 1
disable_existing_loggers: False

formatters:
  verbose:
    format: "%(levelname)s [%(asctime)s] %(name)s:%(process)d:%(thread)d:%(message)s"
  simple:
    format: "%(levelname)s:%(name)s:%(message)s"

handlers:
  'null':
    level: DEBUG
    class: logging.NullHandler
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: simple

loggers:  
  autocheck:
    handlers: [console]
    level: INFO
    propagate: yes
